apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-18T12:26:28Z"
  generation: 1
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "1526"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
  uid: d4173568-93d3-4473-8d0b-f6d9730e76e6
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: gcr.io/terraformlearning-284414/runner@sha256:92d032b5c262f0d6b33325241923d1e07416b30a9aee976684a068cbeede058a
        imagePullPolicy: IfNotPresent
        name: runner-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-02-18T12:26:58Z"
    lastUpdateTime: "2021-02-18T12:26:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-18T12:26:28Z"
    lastUpdateTime: "2021-02-18T12:26:58Z"
    message: ReplicaSet "nginx-1-59cdb567d8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
