apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-dind-deployment
spec:
  selector:
    matchLabels:
      app: runner
  replicas: 2
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: gcr.io/terraformlearning-284414/runner:latest
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: runner-k8s-secret
                  key: gh_token
            - name: REPO_OWNER
              valueFrom:
                secretKeyRef:
                  name: runner-k8s-secret
                  key: repo_owner
            - name: REPO_NAME
              valueFrom:
                secretKeyRef:
                  name: runner-k8s-secret
                  key: repo_name
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          
          
        - name: dind
          image: docker:18.05-dind
          
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}
