apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-18T12:26:28Z"
  generation: 1
  labels:
    app: runner
  name: runner
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
      - image: gcr.io/terraformlearning-284414/runner
        env:
        - name: "ACTIONS_RUNNER_INPUT_URL"
          valueFrom:
            configMapKeyRef:
              key: "repo_url"
              name: "runner-k8s-config"
        - name: "GITHUB_TOKEN"
          valueFrom:
            secretKeyRef:
              key: "gh_token"
              name: "runner-k8s-secret"
        - name: "REPO_OWNER"
          valueFrom:
            configMapKeyRef:
              key: "repo_owner"
              name: "runner-k8s-config"
        - name: "REPO_NAME"
          valueFrom:
            configMapKeyRef:
              key: "repo_name"
              name: "runner-k8s-config"
        imagePullPolicy: IfNotPresent
        name: runner-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

