apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- Deployment.yml
secretGenerator:
- name: runner-k8s-secret
  literals:
  - gh_token=*************
  - repo_owner=samjithin
  - repo_name=terraform
